import CoreGraphics



public struct Constants {
    public static let noId = 1
    public static let db = Db(fullRefresh: false)
    public static let minDefense: Double = 0.001
    public static let minMovementCost: Double = 0.0
    public static let mapWidth: CGFloat = 1000.0 / 3.0
    public static let mapHeight: CGFloat = 1000.0 / 3.0
    public static let terrainTypes: [String: TileDef] = [
        "0": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Grassland,
                     unitType: UnitType.None),
        "1": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "2": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "3": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "4": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "5": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "6": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "7": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "8": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "9": TileDef(tileType: TileType.Terrain,
                     terrainType: TerrainType.Forest,
                     unitType: UnitType.None),
        "10": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "11": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "12": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "13": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "14": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "15": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "16": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "17": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Mountains,
                      unitType: UnitType.None),
        "18": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Mountains,
                      unitType: UnitType.None),
        "19": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Hills,
                      unitType: UnitType.None),
        "20": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "21": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "22": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None),
        "23": TileDef(tileType: TileType.Terrain,
                      terrainType: TerrainType.Forest,
                      unitType: UnitType.None)
    ]
    
    public static let tiles: [String: String] = [
        "0": "Grass",
        "1": "Forest",
        "2": "Forest",
        "3": "Forest",
        "4": "Forest",
        "5": "Forest",
        "6": "Forest",
        "7": "Forest",
        "8": "Forest",
        "9": "Forest",
        "10": "Forest",
        "11": "Forest",
        "12": "Forest",
        "13": "Forest",
        "14": "Forest",
        "15": "Forest",
        "16": "Forest",
        "17": "Mountain",
        "18": "Mountain",
        "19": "Hills",
        "20": "Forest",
        "21": "Forest",
        "22": "Forest",
        "23": "Forest",
        "24": "Water",
        "25": "Tank",
        "26": "Battleship",
        "27": "Explorer",
//        "28": "Forest",
//        "29": "Forest",
    ]
}

